### ISSUE TITLE
npm module is empty

### ISSUE THREAD

**Issue by cowwoc** [anthonynichols/babel-plugin-transform-import-paths#1]
I tried pulling down your module, but all I'm seeing is `package.json` and `README.md`. I don't think you published your actual JS files to npm.

**Comment by anthonynichols** [comment]
@cowwoc I will go back and make sure that the plugin is published. It has been a while since I have visited this codebase, and it looks like it was targeting a bridge version of babel that is out of date. I am going to update this plugin to be compatible with the latest version of babel and use correctly updated dependencies.

Thank you for bringing this to my attention!

**Comment by anthonynichols** [comment]
@cowwoc I updated a few things and re-published. Please check out v1.0.1

![Screen Shot 2019-03-25 at 6 54 27 PM](https://user-images.githubusercontent.com/812470/54961624-7a92a980-4f2f-11e9-8a6d-4f474749dace.png)
